### ISSUE TITLE
AppServer.Start (Socket => {.....

### ISSUE THREAD

**Issue by AcTiViSioN911** [statianzo/Fleck#125]
Hi!

I'm fairly new to learn programming in C # and I would like to know whether you can do better than I did?
AppServer.Start (Socket => {
Socket.OnOpen = () => OnConnect (Socket); 
Socket.OnClose = () => OnDisconnect (Socket); 
Socket.OnMessage = Message => OnNewMessage (Socket, Message);}) ;

But I've seen in "SuperSocket" is implemented as follows:
appServer.NewSessionConnected + = new SessionHandler <WebSocketSession> (OnConnect);
appServer.SessionClosed + = new SessionHandler <WebSocketSession, CloseReason> (OnDisconnect);
appServer.NewMessageReceived + = new SessionHandler <WebSocketSession, string> (OnNewMessage);

Maybe I can do the same? It seems to me, in my way are unnecessary actions.

**Comment by statianzo** [comment]
What you've got for the Fleck code looks right. Creating anonymous functions that create a closure over the "Socket" variable is necessary because of a poor API choice made early in Fleck's creation.

Ideally, OnOpen and OnClose would pass in the socket instance. Maybe in the 1.0 release a breaking change like that could be made and you wouldn't have to wrap your OnConnect and OnDisconnect with anonymous functions.

For now, keep doing what you're doing, and welcome to the C# community!

**Comment by AcTiViSioN911** [comment]
Clearly, thanks!
Your project I liked the most, not as bulky as "SuperSocket", but provides all the same features. If you have commented code, prices would not be for beginners :)
If there are any questions or stumble upon a mistake, I'll let you know. Thanks again!
