### ISSUE TITLE
Support for Streams

### ISSUE THREAD

**Issue by NVentimiglia** [statianzo/Fleck#173]
I would like to pass a memory stream to the  Send method instead of an array of bytes.

The reason is I am currently implementing a recyclable memory stream in my logic layer. There are some performance hits when I acquire the buffer that I would like to avoid.

http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/

**Comment by statianzo** [comment]
If you implement it, I think it sounds like a great addition to Fleck

**Comment by statianzo** [comment]
Some of the needed changes with consuming streams I see:
- indicating where one frame ends and another begins
- indicating where one message ends and another begins
- switching SocketWrapper to use CopyTo [instead of BeginWrite](https://github.com/statianzo/Fleck/blob/master/src/Fleck/SocketWrapper.cs#L152).
- refactoring internal `byte[]` instances to use Streams

**Comment by NVentimiglia** [comment]
Thanks for directions, ill look into this next weekend.
