### ISSUE TITLE
problem with Windows Server 2003

### ISSUE THREAD

**Issue by saeidjoker** [statianzo/Fleck#189]
File: WebSocketServer.cs and in Constructor(int port, string location):
In "socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);" line, there's a bug, and that's with the socket configuration in Windows Server 2003. 

Resolution:
You can check the OS name and leave this line.

**Comment by statianzo** [comment]
Server 2003 doesn't support IPv6. See #150.

If you're interested in a fix being brought in, feel free to submit a pull request.

Rather than checking something as fragile as OS name, it looks like .NET provides a boolean, [System.Net.Sockets.Socket.OSSupportsIPv6](
https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.ossupportsipv6.aspx)

**Comment by erm213** [comment]
I am currently experiencing this problem. I am trying to use this on Windows XP (Pro SP3). 

System.Net.Sockets.Socket.OSSupportsIPv6 will not work, as XP can support IPv6, but is not dual-stack for TCP/IP. In addition, the SocketOptionName.IPv6Only flag is not supported, and trying to get or set it throws an exception. I believe wrapping the 

socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);

in a try catch would allow it to operate on XP, but it will be IPv4 or IPv6 only. Given its age and use, probably not an issue. I am doing some testing, and hope to submit a pull request with the changes.
