### ISSUE TITLE
Is Fleck thread safe?

### ISSUE THREAD

**Issue by rawnsley** [statianzo/Fleck#191]
For instance, can I call methods like [Send](https://github.com/statianzo/Fleck/blob/master/src/Fleck/Interfaces/IWebSocketConnection.cs#L15) from multiple threads simultaneously or do I need to sequence these calls with some sort of lock?

**Comment by statianzo** [comment]
Yes. Fleck is thread safe.

For plaintext connections (ws://), Fleck relies on the internal locking of [NetworkStream](https://msdn.microsoft.com/en-us/library/system.net.sockets.networkstream(v=vs.110).aspx)'s BeginWrite.

For SSL connections (wss://), Fleck uses an internal [QueuedStream](https://github.com/statianzo/Fleck/blob/master/src/Fleck/QueuedStream.cs) that handles locking because .NET's [SslStream](https://msdn.microsoft.com/en-us/library/system.net.security.sslstream(v=vs.110).aspx) doesn't support multiple simultaneous writes.

Either way, no coordination should be necessary by users of the Fleck library.

**Comment by rawnsley** [comment]
@statianzo Awesome. Thanks for the quick response.

**Comment by SirJosh3917** [comment]
How about when recieving connections and messages? Is recieving them thread safe?

**Comment by statianzo** [comment]
@SirJosh3917 incoming messages can happen across multiple threads. If you're sharing state across message callbacks, be sure to lock or use a thread safe data structure.
