### ISSUE TITLE
There is a limit to the size of the message?

### ISSUE THREAD

**Issue by wizardnet972** [statianzo/Fleck#192]
Hi, 
There is a limit to the size of the message?

**Comment by artfulhacker** [comment]
Not really. Since the send and receive are byte arrays you could crash a server with low amount of memory with giant messages. As far as websocket specs in general, see https://tools.ietf.org/html/rfc6455#section-5.2 where it describes max message size as 18,446,744,073,709,551,615 bytes. 

My advice if you want to deal with large messages, break them up and create a sub protocol to handle splitting and merging as well as use a machine with a large amount of memory.
