### ISSUE TITLE
How to distinguish connections？

### ISSUE THREAD

**Issue by daoqiang** [statianzo/Fleck#195]
I would like to achieve one to one to send information, but I can not distinguish between each connection，Using Session？ Using Uid？。I don't know how to use，Can you write a related demo？
THANK YOU!

**Comment by statianzo** [comment]
Every connection has a uid available as socket.ConnectionInfo.Id

**Comment by auladinamica** [comment]
i have thiss scenaario... i need to coonect one client to other via
websocket server..do you have specials  functions  to this scenario.. who
is tbe best way to implement this scenario.. ?  How confirma thaat thw
message sent from a to b id received ok?

Thanks un advance

El 26-03-2017 18:16, "Jason Staten" <notifications@github.com> escribió:

Closed #195 <https://github.com/statianzo/Fleck/issues/195>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/statianzo/Fleck/issues/195#event-1015823647>, or mute
the thread
